import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Indiescrap - Smart Way to Sell Your Scrap",
  description: "Generated by Harsh Gupta ",
   verification: {
    google: "FpdMzMWuwW5HpG9AtlI9EpRwBsiH9L3Dwc-asJ7efhU", // yaha sirf content ka value daalo
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
           <head>
        <meta name="google-site-verification" content="FpdMzMWuwW5HpG9AtlI9EpRwBsiH9L3Dwc-asJ7efhU" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
